services:
  classifier:
    build: .
    container_name: dino
    env_file:
      - .env         # Прокинет твой TOKEN и LOG_LEVEL
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - .:/app       # Опционально: для разработки (код будет обновляться внутри без пересборки)
      - ~/.cache/huggingface:/root/.cache/huggingface # Кэшируем модели, чтобы не качать их каждый раз
    restart: unless-stopped
    networks:
      - artcracker-net

networks:
  artcracker-net:
    external: true
